// Visual markup preserved from the supplied prototype. Behavior is in adjacent controllers.
export default function BrandProfile({
  wide = false
}) {
  return wide ? <><div className={"mock "} data-side={"brand"}><aside className={"side"}><div className={"logo"}>{"Influencer "}<b>{"Mandi"}</b></div><nav className={"nav"}><span className={""}><svg viewBox={"0 0 24 24"} fill={"none"} stroke={"currentColor"} strokeWidth={"1.9"} strokeLinecap={"round"}><circle cx={"11"} cy={"11"} r={"7"}></circle><path d={"M20 20l-3.5-3.5"}></path></svg>{"Discover"}</span><span className={""}><svg viewBox={"0 0 24 24"} fill={"none"} stroke={"currentColor"} strokeWidth={"1.9"} strokeLinejoin={"round"}><path d={"M4 10v4h3l7 4V6l-7 4H4z"}></path><path d={"M18 9.2a4 4 0 010 5.6"}></path></svg>{"Campaigns"}</span><span className={""}><svg viewBox={"0 0 24 24"} fill={"none"} stroke={"currentColor"} strokeWidth={"1.9"} strokeLinejoin={"round"}><path d={"M4 5h16v11H9l-5 4V5z"}></path></svg>{"Chats"}</span><span className={""}><svg viewBox={"0 0 24 24"} fill={"none"} stroke={"currentColor"} strokeWidth={"1.9"} strokeLinejoin={"round"}><path d={"M12 20s-7-4.3-7-9a4 4 0 017-2.6A4 4 0 0119 11c0 4.7-7 9-7 9z"}></path></svg>{"Liked"}</span><span className={"on"}><svg viewBox={"0 0 24 24"} fill={"none"} stroke={"currentColor"} strokeWidth={"1.9"} strokeLinecap={"round"}><circle cx={"12"} cy={"8.5"} r={"3.6"}></circle><path d={"M4.8 20c.9-3.6 3.7-5.5 7.2-5.5S18.3 16.4 19.2 20"}></path></svg>{"Profile"}</span></nav><div className={"tagline"}><div className={"rule"}></div>{"Better creators."}<br />{"Brighter brands."}<div className={"side-links"}><span>{"Billing"}</span><span>{"Support"}</span></div></div></aside><main className={"main"}><div className={"topbar"}><span className={"mode"}><span className={"d"}></span>{"brand mode"}</span><span className={"ava"}>{"C"}</span></div><div className={"head"}><h2>{"Your brand"}</h2><p>{"Your details at a glance, and who is waiting on you"}</p></div><div className={"workspace "}><section className={"surface "}><div className={"row"} style={{
              "padding": "16px",
              "gap": "14px"
            }}><div className={"av sq"} style={{
                "width": "54px",
                "height": "54px",
                "fontSize": "19px"
              }}>{"C"}</div><div className={"tx"}><b style={{
                  "fontSize": "17px"
                }}>{"Chai Point "}<span className={"tick"}>{"✓"}</span></b><small>{"Food & beverage · Mumbai · chaipoint.in"}</small></div></div><div className={"g4"} style={{
              "display": "grid",
              "gridTemplateColumns": "repeat(4,1fr)",
              "gap": "11px"
            }}><div className={"box"}><strong>{"2"}</strong><span>{"Live campaigns"}</span></div><div className={"box"}><strong>{"7"}</strong><span>{"Campaigns run"}</span></div><div className={"box"}><strong>{"24"}</strong><span>{"Creators worked with"}</span></div><div className={"box"}><strong>{"Aug 2026"}</strong><span>{"On Mandi since"}</span></div></div><div className={"action-row"}><span className={"btn solid"}>{"Edit brand"}</span></div></section><div className={"two-col "}><section className={"surface "}><div className={"panel-label"}>{"Your week"}</div><div className={"g3"}><div className={"box"}><strong>{"2"}</strong><span>{"Live"}</span></div><div className={"box"}><strong>{"19"}</strong><span>{"Interested"}</span></div><div className={"box"}><strong>{"3"}</strong><span>{"Matches"}</span></div></div></section><section className={"surface "}><div className={"panel-label"}>{"Waiting on you"}</div><div className={"row"}><div className={"av"}>{"A"}</div><div className={"tx"}><b>{"Ananya Rao"}</b><small>{"84.2K · liked Monsoon menu"}</small></div><span className={"btn ghost"}>{"Review"}</span></div><div className={"row"}><div className={"av"}>{"T"}</div><div className={"tx"}><b>{"Tara Iyer"}</b><small>{"22.4K · liked Monsoon menu"}</small></div><span className={"btn ghost"}>{"Review"}</span></div></section></div></div></main></div></> : <><div className={"ph"} data-side={"brand"}><div className={"top"}><span className={"t"}>{"Brand"}</span></div><div className={"body"}><div className={"row"} style={{
          "padding": "16px",
          "gap": "14px"
        }}><div className={"av sq"} style={{
            "width": "54px",
            "height": "54px",
            "fontSize": "19px"
          }}>{"C"}</div><div className={"tx"}><b style={{
              "fontSize": "17px"
            }}>{"Chai Point "}<span className={"tick"}>{"✓"}</span></b><small>{"Food & beverage · Mumbai"}</small></div></div><div className={"g2"}><div className={"box"}><strong>{"2"}</strong><span>{"Live"}</span></div><div className={"box"}><strong>{"24"}</strong><span>{"Worked with"}</span></div></div><div className={"btn solid"}>{"Edit brand"}</div><span className={"lbl"}>{"Your week"}</span><div className={"g2"}><div className={"box"}><strong>{"19"}</strong><span>{"Interested"}</span></div><div className={"box"}><strong>{"3"}</strong><span>{"Matches"}</span></div></div><span className={"lbl"}>{"Waiting on you"}</span><div className={"row"}><div className={"av"}>{"A"}</div><div className={"tx"}><b>{"Ananya Rao"}</b><small>{"Liked Monsoon menu"}</small></div></div></div><div className={"tabs"}><div className={""}><svg viewBox={"0 0 24 24"} fill={"none"} stroke={"currentColor"} strokeWidth={"1.9"} strokeLinecap={"round"}><circle cx={"11"} cy={"11"} r={"7"}></circle><path d={"M20 20l-3.5-3.5"}></path></svg>{"Discover"}</div><div className={""}><svg viewBox={"0 0 24 24"} fill={"none"} stroke={"currentColor"} strokeWidth={"1.9"} strokeLinejoin={"round"}><path d={"M4 10v4h3l7 4V6l-7 4H4z"}></path><path d={"M18 9.2a4 4 0 010 5.6"}></path></svg>{"Campaigns"}</div><div className={""}><svg viewBox={"0 0 24 24"} fill={"none"} stroke={"currentColor"} strokeWidth={"1.9"} strokeLinejoin={"round"}><path d={"M4 5h16v11H9l-5 4V5z"}></path></svg>{"Chats"}</div><div className={""}><svg viewBox={"0 0 24 24"} fill={"none"} stroke={"currentColor"} strokeWidth={"1.9"} strokeLinejoin={"round"}><path d={"M12 20s-7-4.3-7-9a4 4 0 017-2.6A4 4 0 0119 11c0 4.7-7 9-7 9z"}></path></svg>{"Liked"}</div><div className={""}><svg viewBox={"0 0 24 24"} fill={"none"} stroke={"currentColor"} strokeWidth={"1.9"} strokeLinecap={"round"}><circle cx={"12"} cy={"8.5"} r={"3.6"}></circle><path d={"M4.8 20c.9-3.6 3.7-5.5 7.2-5.5S18.3 16.4 19.2 20"}></path></svg>{"Profile"}</div></div></div></>;
}
