// Visual markup preserved from the supplied prototype. Behavior is in adjacent controllers.
export default function SubscribePage({
  wide = false
}) {
  return wide ? <><div className={"mock "} data-side={"creator"}><aside className={"side"}><div className={"logo"}>{"Influencer "}<b>{"Mandi"}</b></div><nav className={"nav"}><span className={"on"}><svg viewBox={"0 0 24 24"} fill={"none"} stroke={"currentColor"} strokeWidth={"1.9"} strokeLinecap={"round"}><circle cx={"11"} cy={"11"} r={"7"}></circle><path d={"M20 20l-3.5-3.5"}></path></svg>{"Discover"}</span><span className={""}><svg viewBox={"0 0 24 24"} fill={"none"} stroke={"currentColor"} strokeWidth={"1.9"} strokeLinejoin={"round"}><path d={"M4 5h16v11H9l-5 4V5z"}></path></svg>{"Chats"}</span><span className={""}><svg viewBox={"0 0 24 24"} fill={"none"} stroke={"currentColor"} strokeWidth={"1.9"} strokeLinejoin={"round"}><path d={"M12 20s-7-4.3-7-9a4 4 0 017-2.6A4 4 0 0119 11c0 4.7-7 9-7 9z"}></path></svg>{"Liked"}</span><span className={""}><svg viewBox={"0 0 24 24"} fill={"none"} stroke={"currentColor"} strokeWidth={"1.9"} strokeLinecap={"round"}><circle cx={"12"} cy={"8.5"} r={"3.6"}></circle><path d={"M4.8 20c.9-3.6 3.7-5.5 7.2-5.5S18.3 16.4 19.2 20"}></path></svg>{"Profile"}</span></nav><div className={"tagline"}><div className={"rule"}></div>{"Real people."}<br />{"Real stories."}<br />{"Real impact."}<div className={"side-links"}><span>{"Billing"}</span><span>{"Support"}</span></div></div></aside><main className={"main"}><div className={"topbar"}><span className={"mode"}><span className={"d"}></span>{"creator mode"}</span><span className={"ava"}>{"A"}</span></div><div className={"head"}><h2>{"Subscribe"}</h2><p>{"Subscription · Influencer Mandi"}</p></div><div className={"workspace "}><div className={"two-col "}><section className={"surface "}><div className={"panel-label"}>{"One month"}</div><div className={"price"}>{"₹499"}<span>{"/ month"}</span></div><p className={"para"}>{"Same price for creators and brands. No trial. Renews only when you say so."}</p><ul className={"benefits"}><li>{"Unlimited swipes"}</li><li>{"Chat on every match"}</li><li>{"Full profiles"}</li></ul><div className={"btn solid"}>{"Pay with Razorpay"}</div><span className={"btn ghost"}>{"Just let me look around"}</span></section><section className={"surface "}><div className={"panel-label"}>{"Find the right fit"}</div><p className={"scrawl"}>{"one month. that’s it."}</p><h3>{"More discovery."}<br />{"Better conversations."}</h3><p className={"para"}>{"Browse campaigns and creators, express interest, and talk when the interest is mutual."}</p><div className={"annotation"}><span className={"lbl"}>{"Draft pricing"}</span><p>{"₹499, payment provider and access rules are carried over from the supplied prototype and remain subject to confirmation."}</p></div></section></div></div></main></div></> : <><div className={"ph"} data-side={"creator"}><div className={"top"}><span className={"t"}>{"Subscribe"}</span></div>{"\n  "}<p className={"sup"}>{"One month. Same price both sides. No trial."}</p>{"\n  "}<div className={"body mid"}>{"\n    "}<div className={"row"} style={{
          "flexDirection": "column",
          "alignItems": "flex-start",
          "gap": "4px",
          "padding": "20px"
        }}>{"\n      "}<span className={"lbl"}>{"One month"}</span>{"\n      "}<div className={"ttl"} style={{
            "fontSize": "42px"
          }}>{"₹499"}</div>{"\n      "}<small style={{
            "fontSize": "11px",
            "color": "var(--grey)"
          }}>{"Renews only when you say so."}</small></div>{"\n    "}<div className={"chips"}><span className={"chip"}>{"Unlimited swipes"}</span><span className={"chip"}>{"Chat on every match"}</span><span className={"chip"}>{"Full profiles"}</span></div>{"\n    "}<div className={"btn solid"}>{"Pay with Razorpay"}</div>{"\n    "}<div className={"btn ghost"}>{"Just let me look around"}</div>{"\n    "}<p className={"scrawl"} style={{
          "textAlign": "center"
        }}>{"one month. that's it."}</p>{"\n  "}</div></div></>;
}
