// Visual markup preserved from the supplied prototype. Behavior is in adjacent controllers.
export default function SignupPage({
  wide = false
}) {
  return wide ? <><div className={"dsplit"} data-side={"creator"}><div className={"promo"}><div className={"glow"}></div><div className={"mk2"}>{"Influencer"}<br /><em>{"Mandi"}</em></div><div><h2>{"Your next collaboration starts here."}</h2><p>{"Create your account and make room for the right conversations."}</p><p className={"say"}>{"Creators. Brands. Ideas."}</p></div><span className={"lbl"}>{"Real people. Real stories. Real impact."}</span></div><div className={"formside"}><div className={"formcard"}><span className={"lbl"}>{"Welcome to Influencer Mandi"}</span><h3>{"Create account"}</h3><div className={"signup-role-row"}><span className={"signup-role-pill"} data-signup-role-label={"true"}></span><button className={"signup-switch"} type={"button"} data-signup-switch={"true"}></button></div><div className={"fld"}><span className={"lbl"}>{"Name"}</span>{"\n  "}<div className={"in"}>{"Ananya Rao"}</div></div><div className={"fld"}><span className={"lbl"}>{"Email"}</span>{"\n  "}<div className={"in"}>{"ananya@example.com"}</div></div><div className={"fld"}><span className={"lbl"}>{"Password"}</span>{"\n  "}<div className={"in"}>{"••••••••••"}</div><span className={"hint"}>{"At least 8 characters"}</span></div><p className={"quiet"}>{"By creating an account, you accept the "}<span>{"Terms"}</span>{" and "}<span>{"Privacy policy"}</span>{"."}</p><span className={"btn solid"}>{"Create account"}</span><p className={"quiet"}>{"Already have an account? "}<span>{"Log in"}</span></p></div></div></div></> : <><div className={"ph"} data-side={"creator"}><div className={"top"}><span className={"bk"}><svg viewBox={"0 0 24 24"} fill={"none"} stroke={"currentColor"} strokeWidth={"2"} strokeLinecap={"round"} strokeLinejoin={"round"}><path d={"M15 5l-7 7 7 7"}></path></svg></span><span className={"t"}>{"Create account"}</span></div>{"\n  "}<div className={"body"}>{"\n    "}<div className={"signup-role-row"} style={{
          "display": "flex",
          "alignItems": "center",
          "gap": "9px"
        }}>{"\n      "}<span className={"signup-role-pill"} data-signup-role-label={"true"}></span>{"\n      "}<button className={"signup-switch"} type={"button"} data-signup-switch={"true"}></button></div>{"\n    "}<div className={"fld"}><span className={"lbl"}>{"Name"}</span>{"\n  "}<div className={"in"}>{"Ananya Rao"}</div></div>{"\n    "}<div className={"fld act"}><span className={"lbl"}>{"Email"}</span>{"\n  "}<div className={"in"}>{"ananya@example.com"}</div></div>{"\n    "}<div className={"fld"}><span className={"lbl"}>{"Password"}</span>{"\n  "}<div className={"in"}>{"••••••••••"}</div><span className={"hint"}>{"At least 8 characters"}</span></div>{"\n    "}<p className={"sup"} style={{
          "margin": "0"
        }}>{"☐ I accept the terms and privacy policy"}</p>{"\n    "}<div className={"btn solid"}>{"Create account"}</div>{"\n  "}</div></div></>;
}
