import { campaignTimeline } from './campaignDates.js';
import { campCard } from '../../components/cards/cardMarkup.js';
import { gallery, bindGallery } from '../../components/details/MediaGallery.js';
import { openDetail } from '../../components/details/detailsController.js';
import { runtime } from '../../context/runtime.js';
import { CAMPAIGNS, ARCHIVED_CAMPAIGNS } from '../../mocks/campaigns.js';
import { CREATORS } from '../../mocks/creators.js';
import { campaignStatus, setCampaignStatus, campaignHasChats } from './campaignState.js';
import { go } from '../../app/routes.js';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={Edit:'<path d="M4 20h4L19 9l-4-4L4 16v4Z"/>',Pause:'<path d="M9 5v14M15 5v14"/>',Resume:'<path d="m8 5 11 7-11 7Z"/>',Close:'<rect x="5" y="11" width="14" height="9" rx="2"/><path d="M8 11V8a4 4 0 0 1 8 0v3"/>',Delete:'<path d="M4 7h16M10 11v6M14 11v6M6 7l1 13h10l1-13M9 7V4h6v3"/>',followers:'<circle cx="12" cy="8" r="3"/><path d="M5 21v-2a7 7 0 0 1 14 0v2"/>',city:'<path d="M20 10c0 6-8 11-8 11S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>'};
const icon=name=>'<svg class="ce-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+(icons[name]||'')+'</svg>';
export function setupCampaignDetail(root,route){
 if(route!=='campaign')return;
 const c=[...CAMPAIGNS,...ARCHIVED_CAMPAIGNS].find(c=>c.id===(runtime.S.ctx||runtime.S.previewCampaignId))||CAMPAIGNS[0];
 runtime.S.previewCampaignId=c.id;
 const host=root.querySelector('.workspace')||root.querySelector('.body');if(!host)return;
 root.querySelector('.head')?.remove();host.classList.add('campaign-experience');
 runtime.S.campaignPeople ||= {};
 const people=runtime.S.campaignPeople[c.id] ||= CREATORS.slice(0,5).map((p,i)=>({id:p.id,state:i===1?'matched':i===2?'shortlisted':'interested'}));
 let filter='all',query='',view='card';
 const confirm=(label,next)=>{if(next==='Deleted'&&campaignHasChats(c)){const d=document.createElement('dialog');d.className='campaign-confirm';d.innerHTML='<h3>Campaign has ongoing chats</h3><p>This campaign cannot be deleted while it has ongoing chats. You can pause or close it to stop new interest.</p><div class="action-row"><button class="btn ghost">Close</button></div>';d.onkeydown=e=>e.stopPropagation();d.onclose=()=>d.remove();d.querySelector('button').onclick=()=>d.close();document.body.append(d);d.showModal();return;}const d=document.createElement('dialog');d.className='campaign-confirm';d.innerHTML=`<h3>${esc(label)} campaign?</h3><p>${next==='Deleted'?'This removes the campaign from discovery. Existing conversation history remains available.':'This changes whether creators can discover this campaign.'}</p><div class="action-row"><button class="btn ghost">Cancel</button><button class="btn ${next==='Deleted'?'campaign-danger':'solid'}">${esc(label)}</button></div>`;document.body.append(d);d.showModal();const close=()=>{d.close();d.remove();};d.oncancel=e=>{e.preventDefault();close();};d.onkeydown=e=>e.stopPropagation();d.querySelectorAll('button')[0].onclick=close;d.querySelectorAll('button')[1].onclick=()=>{if(!setCampaignStatus(c,next)){close();confirm(label,next);return;}close();if(next==='Deleted')go('campaigns');else draw();};};
 const draw=()=>{
 const status=campaignStatus(c),locked=['Removed by admin','Deleted'].includes(status);
 host.innerHTML=`<button class="ce-back">‹ All campaigns</button><header class="ce-header"><div><h2>${esc(c.title)}</h2><div class="ce-meta"><span class="campaign-status-tag ${status==='Live'?'is-live':''}">${esc(status)}</span><span>${esc(campaignTimeline(c))}</span><span>${esc(c.cat)}</span></div></div><div class="ce-controls"></div></header><section class="ce-panel"><div class="ce-panel-heading"><h3>Preview</h3><div class="ce-switch" role="tablist" aria-label="Campaign preview"><button role="tab" data-view="card">Card</button><button role="tab" data-view="details">Details view</button></div></div><div class="ce-previews" data-view="${view}"><div class="ce-card-pane" role="tabpanel"><p class="ce-label">Card in Discover</p><div class="ce-card">${campCard(c,'front')}</div></div><div class="ce-details-pane" role="tabpanel"><p class="ce-label">Details view</p><article class="ce-detail"><div class="ce-gallery">${gallery(c.images?.length?c.images:c.media||[])}</div><div class="ce-info"><h3>${esc(c.title)}</h3><p class="ce-sub">${esc(c.brand)} · ${esc(c.cat)}</p><p class="ce-brief">${esc(c.brief)}</p>${[['Budget',c.budget],['Timeline',campaignTimeline(c)],['Deliverables',c.del?.join(', ')],['Platforms',c.plat],['Location',c.loc]].map(([label,value])=>`<div class="kv"><span>${label}</span><b>${esc(value)}</b></div>`).join('')}</div></article></div></div></section><section class="ce-panel"><div class="ce-panel-heading"><h3>Creators</h3><span class="ce-total"></span></div><div class="ce-filters" role="tablist" aria-label="Filter creators"></div><div class="ce-toolbar"><input class="in" type="search" aria-label="Search creators" placeholder="Search name, city or content tags"></div><div class="ce-people" aria-live="polite"></div></section>`;
 host.querySelector('.ce-back').onclick=()=>go('campaigns');
 const addControl=(text,action,danger=false)=>{const b=document.createElement('button');b.className='btn ghost'+(danger?' campaign-danger':'');b.innerHTML=icon(text)+'<span>'+esc(text)+'</span>';b.onclick=action;host.querySelector('.ce-controls').append(b);};
 if(!locked){addControl('Edit',()=>go('editcampaign',c.id));if(status!=='Closed'){addControl(status==='Paused'?'Resume':'Pause',()=>confirm(status==='Paused'?'Resume':'Pause',status==='Paused'?'Live':'Paused'));addControl('Close',()=>confirm('Close','Closed'));}}
 if(status!=='Deleted')addControl('Delete',()=>confirm('Delete','Deleted'),true);
 const preview=host.querySelector('.ce-previews');
 const updateView=()=>{preview.dataset.view=view;host.querySelectorAll('[data-view].ce-switch button,.ce-switch [data-view]').forEach(b=>{const selected=b.dataset.view===view;b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1;});};
 host.querySelectorAll('.ce-switch button').forEach(b=>{b.onclick=()=>{if(view===b.dataset.view)return;view=b.dataset.view;updateView();const pane=host.querySelector(view==='card'?'.ce-card-pane':'.ce-details-pane');if(!matchMedia('(prefers-reduced-motion: reduce)').matches)pane.animate([{opacity:0,transform:'translateY(10px)'},{opacity:1,transform:'translateY(0)'}],{duration:240,easing:'ease-out'});};b.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const next=b.parentElement.querySelector(`[data-view="${b.dataset.view==='card'?'details':'card'}"]`);next.click();next.focus();}};});updateView();
 bindGallery(host.querySelector('.ce-gallery'));
 host.querySelectorAll('.ce-gallery [data-act]').forEach(b=>{const direction=b.classList.contains('prev')?-1:1;delete b.dataset.act;b.setAttribute('role','button');b.tabIndex=0;const move=()=>{const track=host.querySelector('.mgal-track');track.scrollBy({left:track.clientWidth*direction,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});};b.onclick=e=>{e.stopPropagation();move();};b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();move();}};});
 const search=host.querySelector('input');search.value=query;search.oninput=()=>{query=search.value;paintPeople();};paintPeople();
 };
 const paintPeople=()=>{
 const filters=host.querySelector('.ce-filters');filters.replaceChildren();
 for(const state of ['all','interested','shortlisted','matched']){const b=document.createElement('button');b.className='ce-filter '+state;b.setAttribute('role','tab');b.setAttribute('aria-selected',String(filter===state));const count=people.filter(p=>state==='all'||p.state===state).length;b.innerHTML=`<i></i>${state[0].toUpperCase()+state.slice(1)} <span>${count}</span>`;b.onclick=()=>{filter=state;paintPeople();};filters.append(b);}
 const matches=people.map((p,i)=>({...CREATORS.find(u=>u.id===p.id),state:p.state,position:i})).filter(p=>(filter==='all'||p.state===filter)&&[p.name,p.loc,...p.tags].join(' ').toLowerCase().includes(query.trim().toLowerCase()));
 host.querySelector('.ce-total').textContent=`${matches.length} shown`;
 const list=host.querySelector('.ce-people');list.replaceChildren();
 if(!matches.length){list.innerHTML='<p class="ce-empty">No creators match these filters.</p>';return;}
 for(const p of matches){const row=document.createElement('article');row.className='ce-person';row.innerHTML=`<div class="ce-avatar">${esc(p.name[0])}</div><button class="ce-person-open"><b>${esc(p.name)}</b><span class="ce-person-meta"><span>${icon("followers")} ${esc(p.followers)}</span><span>${icon("city")} ${esc(p.loc)}</span><span class="ce-state ${p.state}">${p.state[0].toUpperCase()+p.state.slice(1)}</span></span></button><div class="ce-person-actions"></div>`;row.querySelector('.ce-person-open').onclick=()=>openDetail(p.id);const actions=row.querySelector('.ce-person-actions');const action=(label,fn)=>{const b=document.createElement('button');b.className='btn ghost';b.setAttribute('aria-label',label);b.title=label;const paths={'Like back':'<path d="M12 20s-8-4.5-8-10a4.5 4.5 0 0 1 8-3 4.5 4.5 0 0 1 8 3c0 5.5-8 10-8 10Z"/>','Pass':'<path d="m6 6 12 12M18 6 6 18"/>','Remove':'<path d="M4 7h16M9 7V4h6v3M6 7l1 13h10l1-13M10 11v5M14 11v5"/>','Open chat':'<path d="M4 4h16v12H9l-5 4V4Z"/>'};b.innerHTML='<svg class="ce-action-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+paths[label]+'</svg><span>'+label+'</span>';b.onclick=fn;actions.append(b);};const remove=()=>{people.splice(people.findIndex(u=>u.id===p.id),1);paintPeople();};
 if(p.state==='interested'){action('Like back',()=>{people.find(u=>u.id===p.id).state='matched';if(!runtime.S.matches.brand.includes(p.id))runtime.S.matches.brand.push(p.id);runtime.S.campaignChats ||= {};runtime.S.campaignChats[c.id] ||= [];if(!runtime.S.campaignChats[c.id].includes(p.id))runtime.S.campaignChats[c.id].push(p.id);runtime.S.threads[p.id] ||= [];paintPeople();});action('Pass',remove);}else if(p.state==='shortlisted')action('Remove',remove);else action('Open chat',()=>{runtime.S.threads[p.id] ||= [];if(!runtime.S.matches.brand.includes(p.id))runtime.S.matches.brand.push(p.id);runtime.S.openChat=p.id;go('convo',p.id);});list.append(row);}
 };
 draw();
}
